server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # Serve app and support client-side routing
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Optional: gzip
  gzip on;
  gzip_types text/plain text/css application/json application/javascript application/octet-stream image/svg+xml;
  gzip_min_length 256;
}
